services:
  - docker

before_install:
  - docker build -t aswanth06/myreactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true  aswanth06/myreactapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: 
    secure: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
  edge: true
  bucket_name: "elasticbeanstalk-us-east-1-962612810019"
